format = '$custom$all'

follow_symlinks	= false

[time]
disabled = false
time_format = "%R"

[hostname]
ssh_only = false

[custom.wezterm]
description = "Displays the value of the AA variable"
command = "echo \"Pane-$WEZTERM_PANE\""
when = "test -n \"$WEZTERM_PANE\""
style = "bold fg:gray"
format = "[$output]($style): "

[python]
python_binary = [
  '/usr/bin/python3',  # 最優先
  'python3',           # 次の候補
  'python'             # 最後の候補
]
